# Generated by Django 3.1.6 on 2021-02-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumEnt', models.TextField()),
                ('EntNome', models.TextField()),
                ('EntDireccion', models.TextField()),
                ('EntConcello', models.TextField()),
                ('EntCp', models.TextField()),
                ('EntProvincia', models.TextField()),
                ('EntTelefono', models.TextField()),
                ('EntEmail', models.TextField()),
                ('EntCategoria', models.TextField()),
                ('Descr', models.TextField()),
            ],
        ),
    ]
